on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string

name: Make Release
run-name: Releasing v${{ inputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm install
    - name: Set package version
      run: npm version --no-git-tag-version ${{ inputs.version }}
    - name: Build wtr-playwright-commands
      run: npm run build
    - name: Publish wtr-playwright-commands ${{ inputs.version }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
